### ISSUE TITLE
Cannot configure plugin when using Kotlin Gradle DSL

### ISSUE THREAD

**Issue by plnice** [beworker/autoplay#17]
Affected version: 3.0.0-alpha1

To reproduce, apply plugin via `plugins` block:
```
plugins {
    ...
    id("android-autoplay")
}
```
and try to configure it via `autoplay { ... }` block. No variables are available to change due to `AutoplayPublisherExtension` marked as `internal`:

```kotlin
/**
 * Configures the [autoplay][de.halfbit.tools.autoplay.AutoplayPublisherExtension] extension.
 *
 * `autoplay` is not accessible in a type safe way because:
 * - `de.halfbit.tools.autoplay.AutoplayPublisherExtension` is not public
 */
fun org.gradle.api.Project.`autoplay`(configure: Any.() -> Unit): Unit =
    (this as org.gradle.api.plugins.ExtensionAware).extensions.configure("autoplay", configure)
```

**Comment by sergejsha** [comment]
Release `3.0.0-alpha2` has been pushed to maven central. Please let me know whether it fixed the issue.

**Comment by plnice** [comment]
Yes, works correctly with `3.0.0-alpha2`. Thanks!
