### ISSUE TITLE
Invalid JWT Signature

### ISSUE THREAD

**Issue by sulo61** [beworker/autoplay#9]
Hi,
I created a service account in google api console, add role and download key as json, then I linked this project in google play console. Below is an error which I obtained.
I used https://www.browserling.com/tools/json-to-base64 to convert json to base64 text

:app:publishApkRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:publishApkRelease'.
> com.google.api.client.auth.oauth2.TokenResponseException: 400 Bad Request
  {
    "error" : "invalid_grant",
    "error_description" : "Invalid JWT Signature."
  }

**Comment by sergejsha** [comment]
I suspect this error does not relate to base64 encoding, but is rather caused by either wrong key or wrong configuration in google console. Try to use key.json directly as shown down below, to verify that.  If error persists, then it's a key-related issue. 

```groovy
autoplay {
    ...
    secretJsonPath "$projectDir/path/to/your/key.json"
}
```
